C_OBJS=unit_rawcapmgr.c
ASM_OBJS=
COMPONENT=unitrawcapmgr.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcap_raw -lmem_raw $(LIBCOSDEFKERN)

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
